### ISSUE TITLE
Seconds in the countdown

### ISSUE THREAD

**Issue by OrangeXarot** [DrMaxNix/birthdaycountdown#2]
It would be cool if there were seconds in the countdown

btw my birthday it's in 2 days (B

**Comment by DrMaxNix** [comment]
Thank you for your suggestion!
I didn't add a seconds counter because there is not a lot of space in the app..
But my idea would be to show seconds on the last 24h and hide the day counter instead (days are at zero anyways in that time)

**Comment by DrMaxNix** [comment]
I created a card in the todo list: https://github.com/DrMaxNix/birthdaycountdown/projects/1
I'll have to see when I have time to implement it tho..

**Comment by DrMaxNix** [comment]
Another thing is that pushing updates to f-droid takes multiple days so even if I implemented it as soon as possible you'd have to use the apk download on the github repo to have a countdown for your birthday in 2 days :)

**Comment by OrangeXarot** [comment]
> Thank you for your suggestion! I didn't add a seconds counter because there is not a lot of space in the app.. But my idea would be to show seconds on the last 24h and hide the day counter instead (days are at zero anyways in that time)

oh yeah that's smart

**Comment by DrMaxNix** [comment]
I just implemented the seconds counter: https://github.com/DrMaxNix/birthdaycountdown/commit/c8fc997b76a57010d5a4f1ebee5d5051f3dde364
I'll now add some other small things and then version 1.1.0 will be released

**Comment by DrMaxNix** [comment]
Version 1.1.0 is out now!
You can either download the apk directly or wait for the f-droid repo to update

**Comment by DrMaxNix** [comment]
Feature has been implemented, update was pulled by f-droid
