### ISSUE TITLE
new function

### ISSUE THREAD

**Issue by amarradi** [DrMaxNix/birthdaycountdown#4]
Hello, how are you?
I would like to add a few functions to your BirthdayCountdown. What do you think of an event countdown. For example, XYZ days until the next vacation or retirement.

**Comment by DrMaxNix** [comment]
Hi amarradi,
I don't think a feature like this would fit the concept of the app.. _Birthday Countdown_ aims to be a lightweight app which just focuses on your own birthday. Aren't there a lot of better apps out there which allow you to create custom countdowns?
If not, I think it would be a better fit to implement a _multi-countdown-option_ in a new app which doesn't have the _birthday_ intent in mind..

**Comment by amarradi** [comment]
Hey @DrMaxNix ,

Ok, I can see that. Do you fancy a joint project like the calculator for the next holiday or even how long have I been in this world?

**Comment by DrMaxNix** [comment]
Sounds fun tbh :)
But I think this issue is not the right place to discuss this.. Feel free to write me an E-Mail ^^ (address is at my profile page)
